# Offense count: 5
Metrics/AbcSize:
  Max: 45

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 33

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 140

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 52

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 14

# Offense count: 2
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/dobby/configuration.rb'
    - 'lib/dobby/options.rb'
    - 'lib/dobby/runner.rb'
    - 'lib/dobby/formatter/formatter_set.rb'
    - 'lib/dobby/formatter/abstract_formatter.rb'
    - 'lib/dobby/vuln_source/ubuntu.rb'
