sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
before_install:
  - gem update --system
  - gem update --remote bundler
  - sudo apt-get install -y libapt-pkg-dev
install:
  - bundle install
addons:
  apt:
    update: true
