#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'benchmark'
require 'dobby'

cli = Dobby::CLI.new
result = 0

time = Benchmark.realtime do
  result = cli.run
end

puts Rainbow("Finished in #{time.round(3)} seconds").green if cli.options[:debug]
exit result
